"use client";

import { useState, useEffect } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Brain, RefreshCw } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export function AutoGeneratedContext() {
  const [context, setContext] = useState<string[]>([
    "User's name is Harshit.",
    "Harshit is a full stack developer.",
  ]);
  const [isEditing, setIsEditing] = useState(false);
  const [editedContext, setEditedContext] = useState("");
  const { toast } = useToast();

  useEffect(() => {
    setEditedContext(context.join("\n"));
  }, [context]);

  const handleEdit = () => {
    setIsEditing(true);
  };

  const handleSave = () => {
    const newContext = editedContext
      .split("\n")
      .filter((line) => line.trim() !== "");
    setContext(newContext);
    setIsEditing(false);
    toast({
      title: "Context Saved",
      description: "Your edited context has been saved successfully.",
    });
  };

  const handleCancel = () => {
    setEditedContext(context.join("\n"));
    setIsEditing(false);
  };

  const handleRefresh = () => {
    // This is where you would typically call the AI to regenerate the context
    // For now, we'll just simulate it with a toast message
    toast({
      title: "Context Refreshed",
      description: "The AI has regenerated your context.",
    });
  };

  return (
    <Card className="shadow-lg">
      <CardHeader className="space-y-1">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <Brain className="h-5 w-5 text-primary" />
            <CardTitle className="text-2xl">AI-Generated Context</CardTitle>
          </div>
          <Button
            variant="outline"
            size="icon"
            onClick={handleRefresh}
            className="h-8 w-8"
          >
            <RefreshCw className="h-4 w-4" />
          </Button>
        </div>
        <CardDescription>
          Automatically generated context based on your interactions
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {isEditing ? (
          <>
            <Textarea
              value={editedContext}
              onChange={(e) => setEditedContext(e.target.value)}
              className="min-h-[150px] font-mono text-sm"
              placeholder="Enter context, one item per line..."
            />
            <div className="flex justify-end space-x-2">
              <Button variant="outline" onClick={handleCancel}>
                Cancel
              </Button>
              <Button onClick={handleSave}>Save</Button>
            </div>
          </>
        ) : (
          <>
            <ul className="list-disc list-inside space-y-1">
              {context.map((item, index) => (
                <li key={index} className="text-sm">
                  {item}
                </li>
              ))}
            </ul>
            <Button onClick={handleEdit}>Edit Context</Button>
          </>
        )}
      </CardContent>
    </Card>
  );
}
