/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { ApiKeysForm } from "./api-keys-form";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Slider } from "@/components/ui/slider";
import { useToast } from "@/hooks/use-toast";
import {
  Settings2Icon,
  Sparkles,
  Code2,
  Lightbulb,
  Workflow,
  Terminal,
  User,
  Save,
  Sliders,
} from "lucide-react";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { AutoGeneratedContext } from "./auto-generated-context";
import Cookies from "js-cookie";

const PROGRAMMING_LANGUAGES = [
  { value: "typescript", label: "TypeScript" },
  { value: "javascript", label: "JavaScript" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "csharp", label: "C#" },
  { value: "rust", label: "Rust" },
  { value: "go", label: "Go" },
];

const DEFAULT_SYSTEM_PROMPT = `You are a helpful AI assistant with expertise in software development, technology, and problem-solving. You provide clear, concise, and accurate responses while maintaining a professional and friendly demeanor.

Key behaviors:
- Write clean, maintainable, and well-documented code
- Follow best practices and design patterns
- Provide detailed explanations when needed
- Consider security, performance, and scalability
- Suggest improvements and alternatives when appropriate`;

const DEFAULT_USER_CONTEXT = `I am a software developer working on web applications. I have experience with JavaScript and React, and I'm currently learning TypeScript and Next.js. I'm interested in best practices for building scalable and maintainable applications.`;

const AUTO_SAVE_OPTIONS = [
  { id: "technologies", label: "Technologies mentioned" },
  { id: "projects", label: "Projects discussed" },
  { id: "preferences", label: "Code style preferences" },
  { id: "experience", label: "Experience level changes" },
  { id: "interests", label: "New interests or focus areas" },
];

interface Preferences {
  programmingLanguage: string;
  useAnalogies: boolean;
  domainModeling: boolean;
  backwardPlanning: boolean;
  systemPrompt: string;
  customInstructions: string;
  userContext: string;
  autoSaveContext: Record<string, boolean>;
  topP: number;
  topK: number;
  temperature: number;
  maxTokens: number;
}

const DEFAULT_PREFERENCES = {
  programmingLanguage: "typescript",
  useAnalogies: true,
  domainModeling: true,
  backwardPlanning: true,
  systemPrompt: DEFAULT_SYSTEM_PROMPT,
  customInstructions: "",
  userContext: DEFAULT_USER_CONTEXT,
  autoSaveContext: AUTO_SAVE_OPTIONS.reduce<Record<string, boolean>>(
    (acc, option) => ({ ...acc, [option.id]: false }),
    {}
  ),
  topP: 0.9,
  topK: 40,
  temperature: 0.7,
  maxTokens: 1000,
};

export function PreferencesForm() {
  const [preferences, setPreferences] =
    useState<Preferences>(DEFAULT_PREFERENCES);
  const { toast } = useToast();

  useEffect(() => {
    const savedPreferences = Cookies.get("preferences");
    if (savedPreferences) {
      try {
        const parsedPreferences = JSON.parse(savedPreferences);
        setPreferences((prev) => ({
          ...prev,
          ...parsedPreferences,
        }));
      } catch (error) {
        console.error("Error parsing saved preferences:", error);
      }
    }
  }, []);

  const savePreferences = () => {
    Cookies.set("preferences", JSON.stringify(preferences), { expires: 365 }); // Set to expire in 1 year
    toast({
      title: "Preferences Saved",
      description: "Your preferences have been saved successfully.",
    });
  };

  const resetToDefaults = () => {
    setPreferences(DEFAULT_PREFERENCES);
    Cookies.remove("preferences");
    toast({
      title: "Reset to Defaults",
      description: "All preferences have been reset to their default values.",
    });
  };

  return (
    <div className="grid gap-6 md:grid-cols-2">
      <div className="md:col-span-2">
        <ApiKeysForm />
      </div>
      <div className="md:col-span-2">
        <Card className="shadow-lg">
          <CardHeader className="space-y-1">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <Settings2Icon className="h-5 w-5 text-primary" />
                <CardTitle className="text-2xl">Response Preferences</CardTitle>
              </div>
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={resetToDefaults}
                    >
                      Reset to Defaults
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>
                    Reset all preferences to default values
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
            </div>
            <CardDescription>
              Customize how AI responds to your queries
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid gap-4 md:grid-cols-2">
              <div className="space-y-2">
                <div className="flex items-center space-x-2">
                  <Terminal className="h-4 w-4 text-muted-foreground" />
                  <Label className="text-base">
                    Preferred Programming Language
                  </Label>
                </div>
                <Select
                  value={preferences.programmingLanguage}
                  onValueChange={(value) =>
                    setPreferences((prev) => ({
                      ...prev,
                      programmingLanguage: value,
                    }))
                  }
                >
                  <SelectTrigger className="bg-background">
                    <SelectValue placeholder="Select language" />
                  </SelectTrigger>
                  <SelectContent>
                    {PROGRAMMING_LANGUAGES.map((lang) => (
                      <SelectItem key={lang.value} value={lang.value}>
                        {lang.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-4">
                <div className="flex items-center justify-between space-x-2">
                  <div className="flex items-center space-x-2">
                    <Lightbulb className="h-4 w-4 text-muted-foreground" />
                    <Label htmlFor="analogies" className="text-base">
                      Use Analogies for Explanations
                    </Label>
                  </div>
                  <Switch
                    id="analogies"
                    checked={preferences.useAnalogies}
                    onCheckedChange={(checked) =>
                      setPreferences((prev) => ({
                        ...prev,
                        useAnalogies: checked,
                      }))
                    }
                  />
                </div>

                <div className="flex items-center justify-between space-x-2">
                  <div className="flex items-center space-x-2">
                    <Code2 className="h-4 w-4 text-muted-foreground" />
                    <Label htmlFor="domain-modeling" className="text-base">
                      Start with Domain Modeling
                    </Label>
                  </div>
                  <Switch
                    id="domain-modeling"
                    checked={preferences.domainModeling}
                    onCheckedChange={(checked) =>
                      setPreferences((prev) => ({
                        ...prev,
                        domainModeling: checked,
                      }))
                    }
                  />
                </div>

                <div className="flex items-center justify-between space-x-2">
                  <div className="flex items-center space-x-2">
                    <Workflow className="h-4 w-4 text-muted-foreground" />
                    <Label htmlFor="backward-planning" className="text-base">
                      Use Backward Planning
                    </Label>
                  </div>
                  <Switch
                    id="backward-planning"
                    checked={preferences.backwardPlanning}
                    onCheckedChange={(checked) =>
                      setPreferences((prev) => ({
                        ...prev,
                        backwardPlanning: checked,
                      }))
                    }
                  />
                </div>
              </div>
            </div>

            <div className="space-y-2">
              <div className="flex items-center space-x-2">
                <Sparkles className="h-4 w-4 text-muted-foreground" />
                <Label htmlFor="system-prompt" className="text-base">
                  System Prompt
                </Label>
              </div>
              <Textarea
                id="system-prompt"
                placeholder="Enter a system prompt to customize the AI's behavior..."
                value={preferences.systemPrompt}
                onChange={(e) =>
                  setPreferences((prev) => ({
                    ...prev,
                    systemPrompt: e.target.value,
                  }))
                }
                className="min-h-[200px] bg-background font-mono text-sm"
              />
              <p className="text-xs text-muted-foreground">
                The system prompt sets the AI&apos;s personality and behavior.
                It&apos;s sent at the start of each conversation.
              </p>
            </div>

            <div className="space-y-2">
              <div className="flex items-center space-x-2">
                <Settings2Icon className="h-4 w-4 text-muted-foreground" />
                <Label htmlFor="custom-instructions" className="text-base">
                  Custom Instructions
                </Label>
              </div>
              <Textarea
                id="custom-instructions"
                placeholder="Add any specific instructions for the AI..."
                value={preferences.customInstructions}
                onChange={(e) =>
                  setPreferences((prev) => ({
                    ...prev,
                    customInstructions: e.target.value,
                  }))
                }
                className="min-h-[100px] bg-background font-mono text-sm"
              />
              <p className="text-xs text-muted-foreground">
                Custom instructions are additional preferences that modify how
                the AI responds to your queries.
              </p>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card className="shadow-lg">
        <CardHeader className="space-y-1">
          <div className="flex items-center space-x-2">
            <User className="h-5 w-5 text-primary" />
            <CardTitle className="text-2xl">User Context</CardTitle>
          </div>
          <CardDescription>
            Provide information about yourself to help tailor AI responses
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="user-context" className="text-base">
              Your Background and Interests
            </Label>
            <Textarea
              id="user-context"
              placeholder="Describe your experience, current projects, and areas of interest..."
              value={preferences.userContext}
              onChange={(e) =>
                setPreferences((prev) => ({
                  ...prev,
                  userContext: e.target.value,
                }))
              }
              className="min-h-[150px] bg-background"
            />
            <p className="text-xs text-muted-foreground">
              This information helps the AI understand your background and
              provide more relevant responses.
            </p>
          </div>
        </CardContent>
      </Card>

      <Card className="shadow-lg">
        <CardHeader className="space-y-1">
          <div className="flex items-center space-x-2">
            <Save className="h-5 w-5 text-primary" />
            <CardTitle className="text-2xl">
              AI Auto-Save User Context
            </CardTitle>
          </div>
          <CardDescription>
            Configure how the AI automatically updates your user context
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label className="text-base">Auto-save options:</Label>
            {AUTO_SAVE_OPTIONS.map((option: any) => (
              <div key={option.id} className="flex items-center space-x-2">
                <Checkbox
                  id={option.id}
                  checked={preferences.autoSaveContext[option.id]}
                  onCheckedChange={(checked) =>
                    setPreferences((prev) => ({
                      ...prev,
                      autoSaveContext: {
                        ...prev.autoSaveContext,
                        [option.id]: checked,
                      },
                    }))
                  }
                />
                <Label
                  htmlFor={option.id}
                  className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
                >
                  {option.label}
                </Label>
              </div>
            ))}
          </div>
          <p className="text-xs text-muted-foreground">
            Select which aspects of your interactions the AI should
            automatically use to update your user context.
          </p>
        </CardContent>
      </Card>

      <div className="md:col-span-2">
        <Card className="shadow-lg">
          <CardHeader className="space-y-1">
            <div className="flex items-center space-x-2">
              <Sliders className="h-5 w-5 text-primary" />
              <CardTitle className="text-2xl">AI Settings</CardTitle>
            </div>
            <CardDescription>
              Fine-tune the AI&apos;s behavior and output
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid gap-4 md:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor="top-p" className="text-base">
                  Top-p (Nucleus Sampling)
                </Label>
                <Slider
                  id="top-p"
                  min={0}
                  max={1}
                  step={0.01}
                  value={[preferences.topP]}
                  onValueChange={([value]) =>
                    setPreferences((prev) => ({ ...prev, topP: value }))
                  }
                />
                <p className="text-xs text-muted-foreground">
                  Current value: {preferences.topP.toFixed(2)}
                </p>
                <p className="text-xs text-muted-foreground">
                  Controls diversity. Lower values make the output more focused.
                </p>
              </div>
              <div className="space-y-2">
                <Label htmlFor="top-k" className="text-base">
                  Top-k
                </Label>
                <Slider
                  id="top-k"
                  min={1}
                  max={100}
                  step={1}
                  value={[preferences.topK]}
                  onValueChange={([value]) =>
                    setPreferences((prev) => ({ ...prev, topK: value }))
                  }
                />
                <p className="text-xs text-muted-foreground">
                  Current value: {preferences.topK}
                </p>
                <p className="text-xs text-muted-foreground">
                  Limits the number of tokens considered. Lower values increase
                  focus.
                </p>
              </div>
              <div className="space-y-2">
                <Label htmlFor="temperature" className="text-base">
                  Temperature
                </Label>
                <Slider
                  id="temperature"
                  min={0}
                  max={2}
                  step={0.01}
                  value={[preferences.temperature]}
                  onValueChange={([value]) =>
                    setPreferences((prev) => ({ ...prev, temperature: value }))
                  }
                />
                <p className="text-xs text-muted-foreground">
                  Current value: {preferences.temperature.toFixed(2)}
                </p>
                <p className="text-xs text-muted-foreground">
                  Controls randomness. Higher values make output more creative.
                </p>
              </div>
              <div className="space-y-2">
                <Label htmlFor="max-tokens" className="text-base">
                  Max Tokens
                </Label>
                <Slider
                  id="max-tokens"
                  min={1}
                  max={4096}
                  step={1}
                  value={[preferences.maxTokens]}
                  onValueChange={([value]) =>
                    setPreferences((prev) => ({ ...prev, maxTokens: value }))
                  }
                />
                <p className="text-xs text-muted-foreground">
                  Current value: {preferences.maxTokens}
                </p>
                <p className="text-xs text-muted-foreground">
                  Sets the maximum length of the AI&apos;s response.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="md:col-span-2">
        <AutoGeneratedContext />
      </div>

      <div className="md:col-span-2">
        <Button onClick={savePreferences} className="w-full" size="lg">
          Save All Preferences
        </Button>
      </div>
    </div>
  );
}
